
//Demo 1:m relationship and objets-composition
//one customer may place zero or many orders
//Michael Li

import java.util.*;

 //GUI
public class PurchaseView extends javax.swing.JFrame implements IPurchaseView{

    private PurchasePresenter presenter;

    public PurchaseView() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCustomerID = new javax.swing.JLabel();
        jTextFieldCustomerID = new javax.swing.JTextField(8);
        jLabelPhone = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabelFirstName = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelOrderID = new javax.swing.JLabel();
        jTextFieldOrderID = new javax.swing.JTextField(8);//
        jLabelPrice = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField(8);
        jLabelShipper = new javax.swing.JLabel();
        jTextFieldShipper = new javax.swing.JTextField(8);
        jButtonAddOrderToCustomer = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jTextFieldMaxIndex = new javax.swing.JTextField(3);
        jLabelOf = new javax.swing.JLabel();
        jTextFieldCurrentIndex = new javax.swing.JTextField(3);
        jButtonNext = new javax.swing.JButton();
        jButtonSearchByPhone = new javax.swing.JButton();
        jButtonSearchByName = new javax.swing.JButton();
        jButtonDisplayAll = new javax.swing.JButton();
        jButtonStatistics = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer"));

        jLabelCustomerID.setText("CustomerID");

        jTextFieldCustomerID.setEditable(false);
        jTextFieldCustomerID.setText("      ");

        jLabelPhone.setText("Phone");

        jTextFieldPhone.setText("        ");

        jLabelFirstName.setText("FirstName");

        jTextFieldFirstName.setText("       ");

        jLabelLastName.setText("LastName");

        jTextFieldLastName.setText("         ");

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSave)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelFirstName)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFirstName))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelCustomerID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPhone)
                            .addComponent(jLabelLastName))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jTextFieldLastName))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCustomerID)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPhone)
                        .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLastName)
                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSave)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Order"));

        jLabelOrderID.setText("OrderID");

        jTextFieldOrderID.setText("       ");

        jLabelPrice.setText("Price($)");

        jTextFieldPrice.setText("       ");

        jLabelShipper.setText("Shipper");

        jTextFieldShipper.setText("       ");

        jButtonAddOrderToCustomer.setText("Add order to Customer");
        jButtonAddOrderToCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddOrderToCustomerActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("Previous");
        jButtonPrevious.setEnabled(false);//

        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jTextFieldMaxIndex.setText("      ");

        jLabelOf.setText("of");

        jTextFieldCurrentIndex.setText("    ");

        jButtonNext.setText("Next");
        jButtonNext.setEnabled(false);//----
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButtonPrevious)
                        .addGap(31, 31, 31)
                        .addComponent(jTextFieldCurrentIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelOf)
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldMaxIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNext))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelOrderID)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabelPrice)
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelShipper)
                        .addGap(38, 38, 38)
                        .addComponent(jTextFieldShipper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonAddOrderToCustomer)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrderID)
                    .addComponent(jTextFieldOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrice)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelShipper)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldShipper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAddOrderToCustomer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrevious)
                    .addComponent(jTextFieldMaxIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOf)
                    .addComponent(jTextFieldCurrentIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNext))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSearchByPhone.setText("SearchCustomer&OrderByPhone");
        jButtonSearchByPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchByPhoneActionPerformed(evt);
            }
        });

        jButtonSearchByName.setText("SearchCustomer&OrderByName");
        jButtonSearchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchByNameActionPerformed(evt);
            }
        });

        jButtonDisplayAll.setText("DisplayAllCustomer&Order");
        jButtonDisplayAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisplayAllActionPerformed(evt);
            }
        });

        jButtonStatistics.setText("Statistics");
        jButtonStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatisticsActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButtonDisplayAll)
                                .addGap(147, 147, 147)
                                .addComponent(jButtonStatistics))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSearchByPhone)
                                .addGap(62, 62, 62)
                                .addComponent(jButtonSearchByName)))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonExit)
                            .addComponent(jButtonClear))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSearchByName)
                        .addComponent(jButtonSearchByPhone))
                    .addComponent(jButtonClear))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDisplayAll)
                    .addComponent(jButtonStatistics)
                    .addComponent(jButtonExit))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    //save a new ccustomer to DB
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        String firstName=jTextFieldFirstName.getText();
        String lastName=jTextFieldLastName.getText();
        String phone=jTextFieldPhone.getText();
        firstName=firstName.trim();// REMOVE empty characters
        lastName=lastName.trim();
        phone=phone.trim();

        presenter.insertNewCustomer(firstName, lastName, phone);

    }//GEN-LAST:event_jButtonSaveActionPerformed

    // add an order to a customer
    private void jButtonAddOrderToCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddOrderToCustomerActionPerformed

        String orderID=jTextFieldOrderID.getText();
        orderID=orderID.trim();//remove empty characters

        String priceStr=jTextFieldPrice.getText();
        int price=Integer.parseInt(priceStr.trim());

        String shipper=jTextFieldShipper.getText();
        shipper=shipper.trim();

        int customerID=Integer.parseInt(jTextFieldCustomerID.getText());
        presenter.addOrderToCustomer(orderID, price, shipper,customerID);

    }//GEN-LAST:event_jButtonAddOrderToCustomerActionPerformed

    //previous item of orders
    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
		presenter.showPrevious();
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    //next item
    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
      presenter.showNext();
    }//GEN-LAST:event_jButtonNextActionPerformed

    //search by phone
    private void jButtonSearchByPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchByPhoneActionPerformed
        jTextArea1.setText("");

        String phone=jTextFieldPhone.getText();
        phone=phone.trim();

        presenter.performQueryByPhone(phone);

    }//GEN-LAST:event_jButtonSearchByPhoneActionPerformed

    //helper
    private void clearOrderTextField()
    {
	    jTextFieldOrderID.setText("");
	    jTextFieldPrice.setText("");
	    jTextFieldShipper.setText("");
	    jTextFieldMaxIndex.setText("");
		jTextFieldCurrentIndex.setText("");
	}

    //search by first and last name
    private void jButtonSearchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchByNameActionPerformed
          jTextArea1.setText("");

         String firstName=jTextFieldFirstName.getText();
		 firstName=firstName.trim();

		 String lastName=jTextFieldLastName.getText();
		 lastName=lastName.trim();

         presenter.performQueryByName(firstName,lastName);

    }//GEN-LAST:event_jButtonSearchByNameActionPerformed

    //clear textfields
    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldCustomerID.setText("");
        jTextFieldFirstName.setText("");
        jTextFieldLastName.setText("");
        jTextFieldPhone.setText("");

        jTextFieldOrderID.setText("");
        jTextFieldPrice.setText("");
        jTextFieldShipper.setText("");
        jTextArea1.setText("");
        jTextFieldMaxIndex.setText("");
        jTextFieldCurrentIndex.setText("");
        jButtonPrevious.setEnabled(false);//
        jButtonNext.setEnabled(false);

    }//GEN-LAST:event_jButtonClearActionPerformed

    //Display all
    private void jButtonDisplayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisplayAllActionPerformed
        presenter.displayAllCustomerAndOrder();

    }//GEN-LAST:event_jButtonDisplayAllActionPerformed

    //display statistics
    private void jButtonStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatisticsActionPerformed

        clearOrderTextField();
        presenter.statistics();
    }//GEN-LAST:event_jButtonStatisticsActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */

     //define interface methods
     public void bind(PurchasePresenter p)
     {
		presenter=p;
	 }

     //display customers
	 public void displayCustomerEntry(Customers c)
	 {
		jTextFieldCustomerID.setText(""+c.getCustomerID());
		jTextFieldFirstName.setText(c.getFirstName());
		jTextFieldLastName.setText(c.getLastName());
		jTextFieldPhone.setText(c.getPhone());
	 }

     //display orders
	 public void displayOrderEntries(Orders o)
	 {
		jTextFieldOrderID.setText(o.getOrderID());
	    jTextFieldPrice.setText(""+o.getPrice());
		jTextFieldShipper.setText(o.getShipper());
	 }

     //display dat on th etext area
	 public void displayDataTextArea(String s)
	 {
		 jTextArea1.setText(s);
	 }

     //set browsing
	 public void setBrowsing(boolean flag)
	 {
		 jButtonNext.setEnabled(flag);
		 jButtonPrevious.setEnabled(flag);
     }

     //display index
     public void displayMaxAndCurrentIndex(int m, int c)
     {
		 jTextFieldMaxIndex.setText(""+m);
		 jTextFieldCurrentIndex.setText(""+(c+1));
	 }

     //set the latest customer ID
     public void setLatestCustomerID(int id)
     {
		 jTextFieldCustomerID.setText(""+id);
	 }

	 //set customer phone
     public void setCustomerPhone(String p)
     {
		 jTextFieldPhone.setText(p);
	 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddOrderToCustomer;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDisplayAll;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSearchByName;
    private javax.swing.JButton jButtonSearchByPhone;
    private javax.swing.JButton jButtonStatistics;
    private javax.swing.JLabel jLabelCustomerID;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelOf;
    private javax.swing.JLabel jLabelOrderID;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelShipper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCurrentIndex;
    private javax.swing.JTextField jTextFieldCustomerID;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldMaxIndex;
    private javax.swing.JTextField jTextFieldOrderID;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldShipper;
    // End of variables declaration//GEN-END:variables
}
